package com.etiya.crmlite.business.concretes.prod;

import com.etiya.crmlite.business.abstracts.prod.IProductSpecificationCharacteristicUseService;
import com.etiya.crmlite.repositories.prod.IProductSpecificationCharacteristicUseRepository;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@AllArgsConstructor
public class ProductSpecificationCharacteristicUseManager implements IProductSpecificationCharacteristicUseService {
    IProductSpecificationCharacteristicUseRepository productSpecificationCharacteristicUseRepository;
}
